import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/my/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { name: 'home', link: '/' },
  { name: 'Skills', link: '/' },
  { name: 'Projects', link: '/' },
  { name: 'About Me', link: '/' },
  { name: 'Contact', link: '/' },

]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="text-center pt-[150px] px-4">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
